version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db   
  web:
    build:
      context: ./
    depends_on:
      - mongodb
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*



